---
- hosts: all
  tasks:
    - name: Enable third-party sources
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^#\s?(deb\s{1,}.*partner)$'
        line: '\g<1>'
        backrefs: yes
    - name: Update repos and upgrade all packages
      apt:
        update_cache: yes
        upgrade: safe
        force_apt_get: yes
    - import_role:
        name: common
      tags: ['common']
    - import_role:
        name: dev
      tags: ['dev']
    - import_role:
        name: entertainment
      tags: ['entertainment']
    - import_role:
        name: work
      tags: ['work']
    - name: Remove useless apt packages and dependencies
      apt:
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
  become: yes