---
- name: Add Flathup repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.skype.Client
    - com.visualstudio.code