---
- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - default-jdk
    - flatpak
    - git
    - gnome-tweaks
    - keepassxc
    - nautilus-dropbox
    - ubuntu-restricted-extras
    - synaptic
    - terminator
    - vim

- import_tasks: vi.yml
- import_tasks: flatpak.yml