---
- name: Add .local/bin to $PATH
  lineinfile:
    path: ~/.bashrc
    line: PATH="$HOME/.local/bin:$PATH"
  become: no

- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chrome-gnome-shell
    - chromium-browser
    - curl
    - flatpak
    - gnome-tweaks
    - keepassxc
    - nautilus-dropbox
    - ubuntu-restricted-extras
    - synaptic
    - telegram-desktop
    - terminator
    - vim

- import_tasks: flatpak.yml
- import_tasks: snap.yml
- import_tasks: terminator.yml
- import_tasks: vi.yml