---
- name: Create Terminator's configuration folder if it's missing
  file:
    path: ~/.config/terminator
    state: directory

- name: Import Terminator's configuration
  get_url:
    url: '{{ terminator.config }}'
    dest: ~/.config/terminator/config